// Builds dist/: an ES module (React external), its .d.ts, and labready.css, which is the site's
// own two stylesheets concatenated so the components look exactly like labreadypro.com.
import { build } from 'esbuild';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';

rmSync('dist', { recursive: true, force: true });
mkdirSync('dist', { recursive: true });
await build({
    entryPoints: ['src/index.tsx'], bundle: true, format: 'esm', outfile: 'dist/index.js',
    external: ['react', 'react/jsx-runtime'], jsx: 'automatic', target: 'es2019', logLevel: 'warning'
});
execFileSync('node', ['node_modules/typescript/bin/tsc', '-p', 'tsconfig.json'], { stdio: 'inherit' });
const css = ['../assets/labready.css', '../app/app.css']
    .map(p => `/* ---- ${p.replace('../', 'labready/')} ---- */\n` + readFileSync(p, 'utf8')).join('\n\n');
writeFileSync('dist/labready.css', '/* LabReady Pro stylesheet: generated by build.mjs from the site\'s own CSS. Do not edit. */\n\n' + css);
console.log('built dist/index.js, dist/index.d.ts, dist/labready.css');
