/* LabReady Pro module quizzes (draft v0.1).
 * Multiple-choice versions of each module's question bank, used by the module
 * pages (self-study) and by the app (competency method 6, problem solving).
 * `a` is the index of the correct option. Review against your lab's procedures
 * before using a quiz for a competency record.
 */
window.LABREADY_QUIZZES = {
    passMark: 80,
    modules: {
        "01": {
            title: "QC Fundamentals & Westgard Rules",
            questions: [
                { q: "One Level 1 result is +2.3 SD. In a Westgard multirule procedure, what does this mean on its own?",
                  o: ["Reject the run", "It's a warning: check the other rules before deciding", "Recalibrate immediately", "Nothing; ignore it"], a: 1,
                  why: "1-2s is a warning. About 1 in 20 results from a stable system fall outside 2 SD by chance." },
                { q: "Mean 100, SD 2. Which result violates 1-3s?",
                  o: ["104", "105", "107", "95"], a: 2,
                  why: "107 is +3.5 SD. 104 is +2 SD, 105 is +2.5 SD and 95 is −2.5 SD." },
                { q: "Level 1 is +2.4 SD and Level 2 is +2.6 SD in the same run. Which rule is violated?",
                  o: ["R-4s", "2-2s", "4-1s", "None"], a: 1,
                  why: "Two results beyond the same +2 SD limit: 2-2s, which points to systematic error." },
                { q: "Level 1 is +2.2 SD and Level 2 is −2.1 SD in the same run. What error does this suggest?",
                  o: ["Systematic error", "Random error (R-4s)", "Calibration drift", "No error"], a: 1,
                  why: "The range between the two exceeds 4 SD: R-4s, a sign of random error." },
                { q: "Ten consecutive Level 2 results sit below the mean, all within ±2 SD. What does this suggest?",
                  o: ["Nothing, all are in range", "Random error", "A systematic shift (10x)", "A bad control vial only"], a: 2,
                  why: "10x can be violated with every point inside 2 SD. Look for what changed where the run began." },
                { q: "Mean 5.0 mmol/L, SD 0.1 mmol/L. What is the CV?",
                  o: ["0.5%", "2.0%", "5.0%", "20%"], a: 1,
                  why: "CV = SD ÷ mean × 100 = 0.1 ÷ 5.0 × 100 = 2.0%." },
                { q: "Which of these can QC NOT detect?",
                  o: ["Reagent deterioration", "Calibration shift", "A haemolysed patient specimen", "Probe carry-over affecting all samples"], a: 2,
                  why: "Pre-analytical problems in a single specimen are invisible to QC." },
                { q: "A colleague suggests widening the SD limits because QC 'has been running high for weeks'. What's the right response?",
                  o: ["Agree, the limits are too tight", "Reject and investigate; range changes are a documented supervisory decision", "Rerun QC until it passes", "Switch to a new control lot"], a: 1,
                  why: "Widening limits hides a real shift. Any range change is a supervisory decision based on data." }
            ]
        },
        "02": {
            title: "QC Failure Investigation",
            questions: [
                { q: "QC is rejected at 03:00 with the ER waiting. What do you do first?",
                  o: ["Recalibrate", "Rerun the control", "Stop reporting and hold patient results from the run", "Open a new reagent pack"], a: 2,
                  why: "Protect patients first: hold results, notify, move stats to a backup if available. Then investigate." },
                { q: "Why is rerunning the same control until it passes unacceptable?",
                  o: ["It wastes control material", "A repeat can fall in range by chance while the system is still wrong", "The analyser will lock out", "It's only a problem on nights"], a: 1,
                  why: "Repeated reruns hide real error and let it reach patient results." },
                { q: "A control vial was left uncapped on the bench for hours. Its result will most likely be:",
                  o: ["Falsely low", "Falsely high", "Unchanged", "Randomly high or low"], a: 1,
                  why: "Evaporation concentrates the control, so it reads high." },
                { q: "All three levels of ALT shift about +2.5 SD the morning after a new reagent lot was loaded. Where do you look first?",
                  o: ["The Level 1 vial", "The new reagent lot and calibration after the change", "Operator technique", "Room humidity"], a: 1,
                  why: "All levels, same direction, right after a lot change: systematic error from reagent or calibration." },
                { q: "Sodium, potassium and chloride QC all fail on one analyser at the same time. This suggests:",
                  o: ["Three separate problems", "A shared component such as the ISE module or reference electrode", "Bad control material for each", "A pre-analytical problem"], a: 1,
                  why: "Several tests failing together point to what they share." },
                { q: "After recalibrating, Level 2 is back in range. Can you resume patient testing?",
                  o: ["Yes", "Only after all control levels are acceptable", "Only after the supervisor signs", "Only after 24 hours"], a: 1,
                  why: "Verify with all levels before resuming." },
                { q: "Where does the patient look-back window start?",
                  o: ["At midnight", "At the last acceptable QC for that test on that instrument", "At the last calibration", "At the start of the shift"], a: 1,
                  why: "Patients run since the last acceptable QC may be affected." },
                { q: "Rerun results differ from the originals by more than the lab's allowable difference. What must happen?",
                  o: ["Nothing if QC is now fine", "Follow the corrected-report procedure and notify, documenting who and when", "Average the two results", "Report the rerun and discard the original"], a: 1,
                  why: "Corrected reports must be issued and the notification documented." }
            ]
        },
        "03": {
            title: "Calibration & Calibration Verification",
            questions: [
                { q: "What is the difference between calibration and QC?",
                  o: ["They are the same thing", "Calibration sets the signal-to-concentration relationship; QC checks it still holds", "QC sets the relationship; calibration checks it", "Calibration is only for immunoassays"], a: 1,
                  why: "Calibration creates the relationship; QC monitors it." },
                { q: "You've recalibrated creatinine and it passed. Before reporting patients you must:",
                  o: ["Nothing more", "Run all QC levels and confirm they're acceptable", "Run calibration verification", "Wait one hour"], a: 1,
                  why: "A calibration isn't proven until QC confirms it." },
                { q: "A calibration fails with poor agreement between calibrator replicates. This points to:",
                  o: ["Systematic error", "Random error: bubbles, clots, probe, short volume or mixing", "A reagent lot change", "Nothing, recalibrate"], a: 1,
                  why: "Poor replicate agreement is imprecision." },
                { q: "The calibrator was reconstituted with 5.0 mL instead of 3.0 mL. Patient results after calibration will read:",
                  o: ["Falsely low", "Falsely high", "Correctly", "Randomly"], a: 1,
                  why: "The diluted calibrator gives a low signal for its assigned value, so the system over-reports patients." },
                { q: "How many levels are used, at minimum, for calibration verification?",
                  o: ["One", "Two", "Three: low, mid and high across the reportable range", "Five"], a: 2,
                  why: "At least three levels spanning the reportable range." },
                { q: "True or false: if QC is in range, calibration verification isn't needed.",
                  o: ["True", "False"], a: 1,
                  why: "Calibration verification is a separate requirement with its own frequency." },
                { q: "A tech recalibrates four times until a calibration passes. What's wrong?",
                  o: ["Nothing", "Repeating hides the cause; investigate calibrator, reagent and instrument first", "They should have recalibrated five times", "They should have changed the control lot"], a: 1,
                  why: "Same principle as QC: find the cause instead of repeating." },
                { q: "The new calibration factor is 25% different from recent ones, but no flags appeared. You should:",
                  o: ["Accept it; it passed", "Investigate before accepting: calibrator, reagent, instrument and history", "Average it with the last factor", "Ignore factors, only QC matters"], a: 1,
                  why: "A large change signals something different even when the calibration technically passes." }
            ]
        },
        "04": {
            title: "AMR, Reportable Range & Dilutions",
            questions: [
                { q: "What is the analytical measurement range (AMR)?",
                  o: ["The range reported after any dilution", "The range measured directly without dilution or pretreatment", "The reference interval", "The critical value limits"], a: 1,
                  why: "The CRR is what's reported and can extend above the AMR through validated dilution." },
                { q: "50 µL serum is mixed with 450 µL diluent. What's the dilution factor?",
                  o: ["9", "10", "450", "0.1"], a: 1,
                  why: "Total volume ÷ sample volume = 500 ÷ 50 = 10." },
                { q: "After a validated 1:10 manual dilution, lipase reads 180 U/L. What do you report?",
                  o: ["180 U/L", "1800 U/L", "18 U/L", "> AMR"], a: 1,
                  why: "Multiply by the factor, provided 180 is within the AMR." },
                { q: "Glucose reads below the lower AMR limit of 2 mg/dL; the analyser displays 1.2. You report:",
                  o: ["1.2 mg/dL", "< 2 mg/dL", "0 mg/dL", "Nothing"], a: 1,
                  why: "Never report an extrapolated value below the verified range." },
                { q: "An auto-dilution result is 2400 U/L. A tech multiplies it by 5 again. What's wrong?",
                  o: ["Nothing", "The analyser already applied the factor, so the report is five times too high", "They should multiply by 10", "Auto-dilutions can't be reported"], a: 1,
                  why: "Double-applying the factor is a common dilution error." },
                { q: "A diluted sample still reads above the AMR at the maximum validated dilution. You:",
                  o: ["Dilute further with water", "Report as greater than the upper CRR limit", "Report the diluted value × 100", "Reject the sample"], a: 1,
                  why: "Only validated dilutions may be used; beyond that, report '>' per procedure." },
                { q: "In some sandwich immunoassays, a very high concentration gives a falsely low result. This is called:",
                  o: ["Carry-over", "The hook effect", "Matrix effect", "Drift"], a: 1,
                  why: "A dilution that gives a higher corrected result reveals it." },
                { q: "Why choose a dilution that puts the result mid-range rather than near the bottom of the AMR?",
                  o: ["It's faster", "Imprecision near the lower limit gets multiplied by the factor", "Manufacturers require it", "It uses less diluent"], a: 1,
                  why: "Small errors at the low end become large after multiplying." }
            ]
        },
        "05": {
            title: "Reagent Management & Lot-to-Lot Verification",
            questions: [
                { q: "A refrigerated reagent shipment arrives warm. What do you do?",
                  o: ["Put it in the fridge and use it", "Quarantine it, document and notify the supervisor", "Use it only for QC", "Throw it away without recording"], a: 1,
                  why: "Don't use it until the supervisor decides, per procedure." },
                { q: "A reagent is within its box expiry but past on-board stability. Can you use it?",
                  o: ["Yes", "No"], a: 1,
                  why: "Box expiry, on-board stability and calibration stability are separate limits; all must be met." },
                { q: "Why compare patient samples, not just QC, when verifying a new reagent lot?",
                  o: ["QC is too expensive", "QC material may be non-commutable and react differently from patient samples", "Patient samples are more stable", "Regulations forbid using QC"], a: 1,
                  why: "QC can shift when patients don't, or stay flat when patients have shifted." },
                { q: "Where should lot-to-lot patient samples be concentrated?",
                  o: ["Only normal results", "Across the range, with emphasis near medical decision points", "Only very high results", "Any samples left over"], a: 1,
                  why: "Decision points are where a bias changes patient management." },
                { q: "Old lot 126 mg/dL, new lot 136 mg/dL. What is the percent difference?",
                  o: ["+3.9%", "+7.9%", "+10%", "−7.9%"], a: 1,
                  why: "(136 − 126) ÷ 126 = +7.9%." },
                { q: "All QC levels shift about +8% on the new lot, but patient samples agree within 2%. The likely explanation is:",
                  o: ["The new lot is faulty", "QC material is non-commutable with the new lot", "The analyser needs service", "The patients were mislabelled"], a: 1,
                  why: "Patients are comparable; QC targets may need re-establishing (a supervisor decision)." },
                { q: "A new lot fails acceptance criteria and the old lot runs out tomorrow. You should NOT:",
                  o: ["Repeat to exclude handling error", "Put the new lot into use anyway", "Notify the supervisor", "Contact the manufacturer"], a: 1,
                  why: "A failed lot stays quarantined; the supervisor plans the alternative." },
                { q: "Why run old and new lots close together in time?",
                  o: ["To save reagent", "So differences reflect the lot, not specimen deterioration or drift", "It's required by the manufacturer", "To finish before shift change"], a: 1,
                  why: "Timing differences add error unrelated to the lot." }
            ]
        },
        "06": {
            title: "Instrument Correlation & Method Comparison",
            questions: [
                { q: "Two methods have R² = 0.999. Does this prove they agree?",
                  o: ["Yes", "No: R² shows a straight-line relationship, not agreement"], a: 1,
                  why: "A method reading exactly 10% low still gives a near-perfect R²." },
                { q: "What does a slope of 1.08 mean?",
                  o: ["Constant bias of 8 units", "The new method reads about 8% higher, proportionally", "8% imprecision", "Nothing important"], a: 1,
                  why: "Slope is proportional bias." },
                { q: "What does an intercept of −4 mean?",
                  o: ["4% lower", "About 4 units lower across the range (constant bias)", "Poor correlation", "4 outliers"], a: 1,
                  why: "Intercept is constant bias." },
                { q: "Slope 0.95, intercept +2. Predict the new method's result at x = 200.",
                  o: ["190", "192", "202", "210"], a: 1,
                  why: "0.95 × 200 + 2 = 192; bias −8 (−4%)." },
                { q: "Why estimate bias at medical decision points?",
                  o: ["It's easier to calculate", "That's where a difference changes clinical decisions", "Regulations only look there", "Average bias is always zero"], a: 1,
                  why: "Average bias can hide differences at specific concentrations." },
                { q: "One sample differs by 40% while the rest agree. What do you do?",
                  o: ["Delete it", "Investigate (mix-up, clot, interference) and document before excluding", "Average it in", "Repeat the whole study"], a: 1,
                  why: "Never exclude a point just because it doesn't fit." },
                { q: "All samples fall between 80 and 120 mg/dL and R² is 0.82. The problem is:",
                  o: ["The analyser is faulty", "The range is too narrow for reliable regression", "The methods disagree badly", "Too many samples"], a: 1,
                  why: "Add samples across the reportable range." },
                { q: "Glucose comparison: slope 0.93, intercept +2, R² 0.998. The best next step is:",
                  o: ["Accept: R² is excellent", "Investigate the −7% proportional bias (calibration, lots) before accepting", "Reject the new analyser permanently", "Only check the intercept"], a: 1,
                  why: "The bias uses most of the allowable error; investigate and take the data to the director." }
            ]
        },
        "07": {
            title: "Proficiency Testing",
            questions: [
                { q: "Who should test PT samples?",
                  o: ["The most experienced tech", "The personnel who routinely test patients, rotated, in normal workflow", "The supervisor only", "The manufacturer's rep"], a: 1,
                  why: "PT is tested the same way as patients." },
                { q: "A colleague at another lab calls to compare PT results before the deadline. You:",
                  o: ["Share results", "Decline: inter-laboratory communication before the deadline is prohibited", "Share only the passing ones", "Ask the supervisor to share"], a: 1,
                  why: "Communication about PT before the deadline is prohibited." },
                { q: "Your analyser is down. Can you send PT samples to your sister lab to test?",
                  o: ["Yes", "No: referral of PT samples is prohibited"], a: 1,
                  why: "Intentional referral can lead to revocation of the lab's CLIA certificate." },
                { q: "You run patients once. Can you run PT in triplicate and report the average?",
                  o: ["Yes", "No"], a: 1,
                  why: "PT must be handled like patients." },
                { q: "Your calcium event score is 80% but one sample was unacceptable. Do you investigate?",
                  o: ["No, the event passed", "Yes, every unacceptable result is investigated and documented"], a: 1,
                  why: "Passing the event doesn't excuse an unacceptable result." },
                { q: "Failing the same analyte in two consecutive PT events is called:",
                  o: ["Unsatisfactory", "Unsuccessful", "Ungraded", "Acceptable"], a: 1,
                  why: "Unsatisfactory = one event; unsuccessful = two consecutive or two of three." },
                { q: "What should you check first when a PT result is unacceptable?",
                  o: ["The analyser", "Clerical errors: transcription, units, method code", "The PT provider", "The reagent lot"], a: 1,
                  why: "Clerical errors are the most common cause." },
                { q: "The printout reads 2.8 mg/dL but 1.2 was reported for PT magnesium. The failure category is most likely:",
                  o: ["Methodological", "Clerical", "Technical", "PT material"], a: 1,
                  why: "The instrument was right; the reported value wasn't." }
            ]
        },
        "08": {
            title: "Critical Values, Delta Checks & Result Review",
            questions: [
                { q: "During a critical value call, besides giving the result you must:",
                  o: ["Email a copy", "Have the receiver read back the patient identifiers and result", "Ask for a repeat sample", "Call the physician's office"], a: 1,
                  why: "Read-back confirms the result was received correctly." },
                { q: "Which is NOT required when documenting a critical value notification?",
                  o: ["Who was notified", "Date and time", "Read-back confirmed", "The patient's diagnosis"], a: 3,
                  why: "Document result, patient, person notified, date/time, read-back and who notified." },
                { q: "K 7.2, Ca 3.1 mg/dL, ALP 12 U/L on a previously normal outpatient. Most likely cause?",
                  o: ["True hyperkalaemia", "EDTA contamination", "Haemolysis", "Lipaemia"], a: 1,
                  why: "EDTA chelates calcium and the metal cofactors ALP needs, and adds potassium." },
                { q: "Glucose 1100 with low Na, Cl, Ca and protein; the patient has a D5 drip. Most likely cause?",
                  o: ["DKA", "Dextrose IV contamination", "Lab error", "Delayed processing"], a: 1,
                  why: "Very high glucose with everything else diluted: drawn above the drip." },
                { q: "Most delta check failures turn out to be:",
                  o: ["Mislabelled specimens", "Real clinical changes", "Analyser errors", "Contamination"], a: 1,
                  why: "The check prompts review; it isn't an automatic rejection." },
                { q: "You suspect a specimen belongs to a different patient. You:",
                  o: ["Report with a comment", "Don't release; follow procedure and request recollection", "Report the results you believe", "Relabel it"], a: 1,
                  why: "Suspected wrong-blood-in-tube specimens are not reported." },
                { q: "You can't reach the nurse or physician within the time limit. You:",
                  o: ["Try again tomorrow", "Follow the escalation policy and document every attempt", "Leave a voicemail and stop", "Email the result"], a: 1,
                  why: "Escalate per policy and document." },
                { q: "A sample sat unspun for six hours at room temperature. Which result is falsely low?",
                  o: ["Potassium", "Glucose", "Sodium", "Creatinine"], a: 1,
                  why: "Glycolysis consumes glucose; potassium may rise." }
            ]
        },
        "09": {
            title: "Pre-Analytical Quality & Specimen Integrity",
            questions: [
                { q: "How many patient identifiers must a specimen have?",
                  o: ["One", "At least two, matching the order", "Three", "None if it's a stat"], a: 1,
                  why: "Two identifiers is the minimum." },
                { q: "Which analyte is falsely increased by haemolysis?",
                  o: ["Sodium", "Potassium", "Glucose", "Albumin"], a: 1,
                  why: "Red cells release potassium (also LD, AST, phosphate, Mg)." },
                { q: "Sodium 126 on a grossly lipaemic sample measured by indirect ISE. What might be happening?",
                  o: ["True hyponatraemia", "Pseudohyponatraemia from volume displacement", "Haemolysis", "IV contamination"], a: 1,
                  why: "Confirm with direct ISE or follow procedure." },
                { q: "Why does order of draw matter?",
                  o: ["Faster collection", "It prevents additive carryover between tubes", "It keeps tubes warm", "It's only for blood cultures"], a: 1,
                  why: "For example, EDTA carried into a serum tube." },
                { q: "A sample drawn above a normal saline drip shows:",
                  o: ["Very high glucose", "High Na and Cl with other analytes diluted", "High potassium only", "No change"], a: 1,
                  why: "Saline adds sodium and chloride and dilutes everything else." },
                { q: "Fibrin in a serum sample can cause:",
                  o: ["Falsely high results", "Short sampling (falsely low results) and probe alarms", "Haemolysis", "Lipaemia"], a: 1,
                  why: "The probe aspirates too little sample." },
                { q: "A patient's samples are repeatedly haemolysed despite good collection. Consider:",
                  o: ["Rejecting all future samples", "In-vivo haemolysis, and tell the clinical team", "A faulty centrifuge only", "Ignoring it"], a: 1,
                  why: "True haemolysis is clinically important." },
                { q: "The ward says a specimen with one identifier is 'definitely correct'. Can you relabel it?",
                  o: ["Yes", "Only if your procedure explicitly allows it, with documentation; usually no"], a: 1,
                  why: "Follow the mislabel procedure." }
            ]
        },
        "10": {
            title: "Maintenance, Troubleshooting & Downtime",
            questions: [
                { q: "Weekly maintenance was done but not recorded. As far as an inspector is concerned:",
                  o: ["It was done", "It can't be shown to have been done", "It doesn't matter", "Only monthly maintenance counts"], a: 1,
                  why: "Unrecorded maintenance can't be demonstrated." },
                { q: "A probe clot alarm occurs on one sample. Which results are usually affected?",
                  o: ["The whole run", "That sample's tests; short sampling reads falsely low", "Nothing", "Only QC"], a: 1,
                  why: "Check the specimen and rerun." },
                { q: "The reaction temperature was out of range for 40 minutes before an alarm. What's affected?",
                  o: ["Only the next sample", "Potentially every result in that window", "Nothing", "Only QC"], a: 1,
                  why: "Treat it like a QC failure look-back." },
                { q: "An error has been cleared five times this shift. The right response is:",
                  o: ["Keep clearing it", "Investigate or escalate: recurring errors indicate an underlying problem", "Turn off the alarm", "Wait for the next shift"], a: 1,
                  why: "Recurring errors are data." },
                { q: "When should you call service?",
                  o: ["For every error", "When the problem is beyond operator level, recurs, or the manual says to", "Never", "Only at night"], a: 1,
                  why: "Have error codes, serial number and what you tried ready." },
                { q: "Before resuming patient testing after a repair you need:",
                  o: ["Nothing", "Function checks, calibration if required, and acceptable QC", "A new reagent lot", "The director's signature"], a: 1,
                  why: "Verify before resuming." },
                { q: "During downtime, which requests are prioritised?",
                  o: ["Outpatients", "ED, ICU, critical and stat requests", "Oldest first", "Whatever is easiest"], a: 1,
                  why: "Follow the downtime plan's priorities." },
                { q: "When the LIS comes back after downtime you must:",
                  o: ["Nothing", "Back-enter and verify manual results, clear the backlog and document", "Delete manual reports", "Rerun every sample"], a: 1,
                  why: "Manual results must end up in the LIS, verified." }
            ]
        }
    }
};
